---
# Copyright 2017, OpenIO SAS.
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Wait for services to be up
  uri:
    url: "{{ item }}"
    method: "HEAD"
    status_code: 300
  with_items:
    - "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}"
    - "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-public']['http-socket'] }}"
  register: _wait_check
  until: _wait_check | success
  retries: 12
  delay: 5

- name: Bootstrap keystone admin and endpoint
  command: |
     {{ openio_keystone_bindir }}/keystone-manage bootstrap \
     --bootstrap-username {{ openio_keystone_admin_user_name }} \
     --bootstrap-password {{ openio_keystone_auth_admin_password }} \
     --bootstrap-project-name {{ openio_keystone_admin_tenant_name }} \
     --bootstrap-role-name {{ openio_keystone_role_name }} \
     --bootstrap-service-name {{ openio_keystone_service_name }} \
     --bootstrap-region-id {{ openio_keystone_service_region }} \
     --bootstrap-admin-url {{ openio_keystone_service_adminuri }} \
     --bootstrap-public-url {{ openio_keystone_service_publicuri }} \
     --bootstrap-internal-url {{ openio_keystone_service_internaluri }}
  become: yes
  become_user: "{{ openio_keystone_system_user_name }}"
  changed_when: false
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create a service tenant
- name: Ensure service tenant
  keystone:
    command: "ensure_tenant"
    login_user: "{{ openio_keystone_admin_user_name }}"
    login_password: "{{ openio_keystone_auth_admin_password }}"
    login_project_name: "{{ openio_keystone_admin_tenant_name }}"
    endpoint: "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}/v{{ openio_keystone_api_version }}"
    ignore_catalog: True
    tenant_name: "{{ openio_keystone_service_tenant_name }}"
    description: "{{ openio_keystone_service_description }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Add the default user role
- name: Ensure default keystone user role
  keystone:
    command: "ensure_role"
    login_user: "{{ openio_keystone_admin_user_name }}"
    login_password: "{{ openio_keystone_auth_admin_password }}"
    login_project_name: "{{ openio_keystone_admin_tenant_name }}"
    endpoint: "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}/v{{ openio_keystone_api_version }}"
    ignore_catalog: True
    role_name: "{{ openio_keystone_default_role_name }}"
  register: add_member_role
  when: not openio_keystone_service_in_ldap | bool
  until: add_member_role|success
  retries: 5
  delay: 10

# Create a service
- name: Ensure Keystone Service
  keystone:
    command: "ensure_service"
    login_user: "{{ openio_keystone_admin_user_name }}"
    login_password: "{{ openio_keystone_auth_admin_password }}"
    login_project_name: "{{ openio_keystone_admin_tenant_name }}"
    endpoint: "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}/v{{ openio_keystone_api_version }}"
    ignore_catalog: True
    service_name: "{{ openio_keystone_service_name }}"
    service_type: "{{ openio_keystone_service_type }}"
    description: "{{ openio_keystone_service_description }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create a service user
- name: Ensure Keystone user
  keystone:
    command: "ensure_user"
    login_user: "{{ openio_keystone_admin_user_name }}"
    login_password: "{{ openio_keystone_auth_admin_password }}"
    login_project_name: "{{ openio_keystone_admin_tenant_name }}"
    endpoint: "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}/v{{ openio_keystone_api_version }}"
    ignore_catalog: True
    user_name: "{{ openio_keystone_service_user_name }}"
    tenant_name: "{{ openio_keystone_service_tenant_name }}"
    password: "{{ openio_keystone_service_password }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Add a role to the user
- name: Ensure Keystone user to Admin role
  keystone:
    command: "ensure_user_role"
    login_user: "{{ openio_keystone_admin_user_name }}"
    login_password: "{{ openio_keystone_auth_admin_password }}"
    login_project_name: "{{ openio_keystone_admin_tenant_name }}"
    endpoint: "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}/v{{ openio_keystone_api_version }}"
    ignore_catalog: True
    user_name: "{{ openio_keystone_service_user_name }}"
    tenant_name: "{{ openio_keystone_service_tenant_name }}"
    role_name: "{{ openio_keystone_role_name }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create an endpoint
- name: Update Keystone endpoint
  keystone:
    command: "ensure_endpoint"
    login_user: "{{ openio_keystone_admin_user_name }}"
    login_password: "{{ openio_keystone_auth_admin_password }}"
    login_project_name: "{{ openio_keystone_admin_tenant_name }}"
    endpoint: "http://{{ openio_keystone_uwsgi_bind['keystone-wsgi-admin']['http-socket'] }}/v{{ openio_keystone_api_version }}"
    ignore_catalog: True
    region_name: "{{ openio_keystone_service_region }}"
    service_name: "{{ openio_keystone_service_name }}"
    service_type: "{{ openio_keystone_service_type }}"
    endpoint_list:
      - url: "{{ openio_keystone_service_publicuri }}"
        interface: "public"
      - url: "{{ openio_keystone_service_internaluri }}"
        interface: "internal"
      - url: "{{ openio_keystone_service_adminuri }}"
        interface: "admin"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10
